# Generated by Django 2.2.3 on 2019-07-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='作者姓名')),
                ('info', models.CharField(blank=True, max_length=255, null=True, verbose_name='作者简介')),
                ('image', models.ImageField(default='static/img/name.png', upload_to='static/img/', verbose_name='作者图片')),
            ],
            options={
                'verbose_name': '作者表',
                'verbose_name_plural': '作者表',
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='书名')),
                ('image', models.ImageField(upload_to='static/img/', verbose_name='封面')),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='租书价格')),
                ('amount', models.IntegerField(default=0, verbose_name='可借数量')),
                ('publish_date', models.DateField(verbose_name='出版日期')),
                ('pages', models.IntegerField(verbose_name='书籍页数')),
                ('stars', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='推荐指数')),
                ('desc', models.CharField(max_length=255, verbose_name='书本简介')),
                ('b_money', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='所需押金')),
                ('buy_price', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='购买价格')),
                ('publishers', models.CharField(max_length=64, verbose_name='出版社')),
                ('author', models.ManyToManyField(db_constraint=False, related_name='books', to='book.Author')),
            ],
            options={
                'verbose_name': '图书表',
                'verbose_name_plural': '图书表',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, '中国文学'), (2, '外国文学')], default=1, verbose_name='图书分类')),
            ],
            options={
                'verbose_name': '图书分类表',
                'verbose_name_plural': '图书分类表',
                'db_table': 'book_category',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, '文学类'), (2, '流行'), (3, '文化'), (4, '生活'), (5, '经管'), (6, '科技')], verbose_name='书籍标签')),
                ('book', models.ManyToManyField(db_constraint=False, related_name='tag', to='book.Book')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
                'db_table': 'home_tags',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='book.Category'),
        ),
    ]
