# Generated by Django 2.2.3 on 2019-07-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190729_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img/', verbose_name='封面'),
        ),
    ]
