# Generated by Django 2.2.3 on 2019-08-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookcart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcart',
            options={'verbose_name': '购物车表', 'verbose_name_plural': '购物车表'},
        ),
    ]
