# Generated by Django 2.2.3 on 2019-08-05 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0005_auto_20190804_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='租借数量')),
                ('rent_time', models.DateTimeField(auto_now_add=True, verbose_name='租书日期')),
                ('back_time', models.DateField(null=True, verbose_name='还书日期')),
                ('max_time', models.IntegerField(default=30)),
                ('book', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rented', to='book.Book')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rented', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '租借',
                'verbose_name_plural': '租借',
                'db_table': 'book_rent',
            },
        ),
        migrations.CreateModel(
            name='Ordered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='租借数量')),
                ('a_money', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='预约价格')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='预约日期')),
                ('book', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordered', to='book.Book')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'db_table': 'book_ordered',
            },
        ),
    ]
