# Generated by Django 2.2.3 on 2019-08-04 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alipay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_num', models.CharField(max_length=64, verbose_name='订单号')),
                ('pay_status', models.BooleanField(default=False, verbose_name='订单状态')),
                ('pay_user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alipay', to=settings.AUTH_USER_MODEL, verbose_name='支付者信息')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'book_order',
            },
        ),
    ]
