# Generated by Django 2.2.3 on 2019-08-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alipay',
            table='book_alipay',
        ),
    ]
