# Generated by Django 2.2.3 on 2019-07-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img/name.png', upload_to='avatar/', verbose_name='用户头像'),
        ),
    ]
